### ISSUE TITLE
Zjistit možnosti a stanovisko k existenci domény data.cuni.cz pro publikaci dat

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dokumentace#2]

**Comment by JiriSkalicky** [comment]
**[04. 10. 2021]** Odeslán dotaz na ÚVT

**Comment by JiriSkalicky** [comment]
**[05.10.2021]** V dozírné době nebude realizováno.
-> navrhuji vystavět celé řešení pouze na úrovni MFF UK
