### ISSUE TITLE
Vydolovat číselník pracovišť z DB WhoIS

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dokumentace#3]
Zatím číselník bereme z webu mff.cuni.cz, cestu toku dat ale chceme napřimovat.

**Comment by JiriSkalicky** [comment]
Existuje jen 8 mzdových tříd pro "Ostatní pracovníky" [https://cuni.cz/UK-8897.html]
Prosím @jakubklimek  o úpravu ve specifikaci (odstranit třídy 10 až 15).

**Comment by JiriSkalicky** [comment]
Pardon, provedena chybná editace issue.

**Comment by jakubklimek** [comment]
Viz #16
