### ISSUE TITLE
Ověřit u DERS, jak čerpají číselníky

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dokumentace#8]
- mzdové třídy
- klasifikace zaměstnání

**Comment by JiriSkalicky** [comment]
**[04. 10. 2021]** Odeslán email DERS
**[04. 10. 2021]** Předběžná informace od DERS: osoby a pracoviště jsou vytěžovány z WhoIS, ostatní číselníky zavedeny jednorázově do správy číselníků
